version: '3'
services:

  redis-cache:
    image: redis
    working_dir: /cache
    command: ./cache.conf --daemonize no
    volumes:
        - ./cache:/cache

  redis-indexing:
    image: redis
    working_dir: /indexing
    command: ./indexing.conf --daemonize no
    volumes:
        - ./indexing:/indexing

  splash:
    image: "scrapinghub/splash:3.5.0"
    ports:
        - "8050:8050"
        - "5023:5023"
    command: --disable-private-mode

  scraper:
      image: "scrape-service"
      security_opt:
         - seccomp:chrome.json
      ports:
         - "3000:3000"

  lookyloo:
    build: .
    working_dir: /lookyloo
    tty: true
    environment:
        - SPLASH_URL_DOCKER=http://splash:8050
        - SCRAPE_URL_DOCKER=http://scraper:3000
    command:
        - /bin/sh
        - -c
        - |
            poetry run start
            tail -F ./LICENSE
    volumes:
        - ./cache:/lookyloo/cache
        - ./indexing:/lookyloo/indexing
        - ./scraped:/lookyloo/scraped
        - ./discarded:/lookyloo/discarded_captures
        - ./user_agents:/lookyloo/user_agents
        - ./config:/lookyloo/config
    ports:
        - "5100:5100"
    links:
        - "redis-cache"
        - "redis-indexing"
        - "splash"
        - "scraper"
